import type { restaurantContents } from "./content";

export type RestaurantEntry = {
  name: keyof typeof restaurantContents;
  starred?: true;
  unvisited?: true;
};

export type SubGenre = {
  name: string;
  restaurants: RestaurantEntry[];
};

export type Genre = {
  name: string;
  restaurants?: RestaurantEntry[];
  subgenres?: SubGenre[];
};

export const genres: Genre[] = [
  {
    name: "らーめん",
    subgenres: [
      {
        name: "まぜそば・油そば",
        restaurants: [
          { name: "油虎", starred: true },
          { name: "むじゃき" },
          { name: "貝出汁 まぜそば 虎巴徠" },
        ],
      },
      {
        name: "鬼系",
        restaurants: [
          { name: "鬼者語", starred: true },
          { name: "芛堂寺（いどうじ）", starred: true },
          { name: "論露に不二", unvisited: true },
          { name: "sois", unvisited: true },
        ],
      },
      {
        name: "二郎系",
        restaurants: [
          { name: "異国龍", starred: true },
          { name: "麺処はいから", starred: true },
          { name: "豚男爵" },
          { name: "龍郎" },
          { name: "銀のしずく" },
          { name: "ハイマウントJ", unvisited: true },
          { name: "俺の生きる道W" },
          { name: "俺の生きる道 @つくば店", unvisited: true },
        ],
      },
      {
        name: "家系",
        restaurants: [
          { name: "王道家直系 家系ラーメン がく", starred: true },
          { name: "ラーメン清六家 @筑波大学店" },
          { name: "ラーメン清六家 @つくばキュート店" },
          { name: "横浜家系ラーメン 魂心家 @つくば店" },
        ],
      },
      {
        name: "淡麗系・醤油・煮干し",
        restaurants: [
          { name: "中華そば JUN-CHAN", starred: true },
          { name: "松屋製麺所", starred: true },
          { name: "松屋食堂", starred: true },
          { name: "麺屋 必道", starred: true },
          { name: "煮干中華ソバ イチカワ", starred: true },
          { name: "いっとく", starred: true },
          { name: "らぁめん 喜乃壺（きのこ）" },
          { name: "喜元門 @研究学園店" },
          { name: "中華そば 騰匠俐" },
          { name: "自家製麺 名無し", unvisited: true },
          { name: "中華そばビート", unvisited: true },
          { name: "らぁめん ゑびすや" },
          { name: "麺と酒 なないち" },
        ],
      },
      {
        name: "味噌",
        restaurants: [
          { name: "麺や 蒼 AOI", starred: true },
          { name: "旭川らあめん やまる", starred: true },
          { name: "麺屋とみよし" },
          { name: "味噌のジョー @つくば本店 " },
        ],
      },
      {
        name: "鶏",
        restaurants: [
          { name: "鶏々", starred: true },
          { name: "特級鶏蕎麦 龍介 @土浦学園通り店", starred: true },
          { name: "特級鶏蕎麦 龍介 @テクノパーク桜店", starred: true },
          { name: "麺匠 伊助" },
        ],
      },
      {
        name: "未分類",
        restaurants: [
          { name: "七福軒", starred: true },
          { name: "はりけんラーメン", starred: true },
          { name: "丸源", starred: true },
          { name: "千里", starred: true },
          { name: "甲殻堂", starred: true },
          { name: "ちゅら食堂", starred: true },
          { name: "ラーメン刻（とき）" },
          { name: "つけそば 丸長" },
          { name: "ごう家" },
          { name: "東京背脂 銀の豚" },
          { name: "活龍大衆麺処 真壁屋" },
          { name: "活龍 @本店" },
          { name: "活龍 @竹園店" },
          { name: "博多拉麺 一休" },
          { name: "天下一品 @つくば店" },
          { name: "特級中華蕎麦 洋介 @天久保店" },
          { name: "麺屋秀彬" },
          { name: "担々麺ロシュー" },
          { name: "らーめん三水" },
          { name: "ラーメンショップ ○化 @つくば店" },
          { name: "麺や松辰" },
          { name: "盛清六", starred: true },
          { name: "麺屋とどろき", starred: true },
          { name: "麺 the Tokyo" },
          { name: "和の国 KAGUYA RAMEN" },
          { name: "ゆきむら亭 つくば西店", unvisited: true },
          { name: "麺処 明り", unvisited: true },
          { name: "屋台ラーメン桜", unvisited: true },
          { name: "麺や小五郎", unvisited: true },
          { name: "ららららーめんや", unvisited: true },
          { name: "らーめんICHI", unvisited: true },
        ],
      },
    ],
  },
  {
    name: "中華",
    restaurants: [
      { name: "北方園", starred: true },
      { name: "福軒餃子", starred: true },
      { name: "ファッションラーメン大元", starred: true },
      { name: "えん弥 @桜ニュータウン店", starred: true },
      { name: "えん弥 @東光台店", starred: true },
      { name: "百香亭 @筑波大学店", starred: true },
      { name: "百香亭 @本店", starred: true },
      { name: "大成軒" },
      { name: "金の馬結" },
      { name: "川聚閣（せんしゅうかく）" },
      { name: "麺八" },
      { name: "麻辣十食", unvisited: true },
      { name: "麺屋 湯火", unvisited: true },
    ],
  },
  {
    name: "和食・定食",
    subgenres: [
      {
        name: "定食",
        restaurants: [
          { name: "夢屋", starred: true },
          { name: "くぅべ", starred: true },
          { name: "定食や ふくろう", starred: true },
          { name: "めしや 益さん", starred: true },
          { name: "れいちゃんの食小屋" },
          { name: "あじよし", unvisited: true },
          { name: "魚八", unvisited: true },
          { name: "鬼屋 @つくば本店" },
          { name: "大戸屋 @イーアスつくば店" },
          { name: "大戸屋 @BiViつくば店" },
          { name: "豚飯坊屋", unvisited: true },
        ],
      },
      {
        name: "とんかつ",
        restaurants: [
          { name: "とんかつとんQ @つくば本店", starred: true },
          { name: "とんかつとんQ @イーアスつくば店", starred: true },
          { name: "とんとこ豚", starred: true },
          { name: "純平" },
          { name: "かつ太郎本店 つくば学園店", unvisited: true },
        ],
      },
      {
        name: "うどん・そば",
        restaurants: [
          { name: "カレーうどん ZEYO.", starred: true },
          { name: "釜揚うどん店 あおやま" },
          { name: "日本橋太切りつけそば たぐり" },
          { name: "和創旬彩 たかぼ", unvisited: true },
          { name: "おそば 増田屋", unvisited: true },
        ],
      },
      {
        name: "寿司・うなぎ",
        restaurants: [
          { name: "蛇の目寿司", starred: true },
          { name: "誠寿司" },
          { name: "はま寿司 @つくば研究学園店" },
          { name: "はま寿司 @つくば小野崎店" },
          { name: "スシロー @つくば学園の森店" },
          { name: "魚べい @つくば研究学園店" },
          { name: "鰻専門店 うなつく", unvisited: true },
          { name: "松乃家", unvisited: true },
          { name: "つくば蕎麦物語 一成", unvisited: true },
        ],
      },
      {
        name: "お好み焼き",
        restaurants: [
          { name: "三八", starred: true },
          { name: "一太郎" },
          { name: "より味ち", unvisited: true },
        ],
      },
      {
        name: "弁当",
        restaurants: [
          { name: "仲々" },
          { name: "桃ちゃん弁当", unvisited: true },
          { name: "とんかつ弁当かつ大", unvisited: true },
          { name: "おふくろさん弁当", unvisited: true },
        ],
      },
      {
        name: "丼ぶり",
        restaurants: [
          { name: "クラレット", starred: true },
          { name: "天丼屋ふくすけ", starred: true },
          { name: "RanRan", starred: true },
          { name: "伝説のすた丼 @つくば大学店" },
        ],
      },
    ],
  },
  {
    name: "各国料理",
    subgenres: [
      {
        name: "洋食",
        restaurants: [
          { name: "フライパン", starred: true },
          { name: "カフェヨン: ハンバーグ", starred: true },
          { name: "フライングガーデン: ハンバーグ", starred: true },
          { name: "ドルフ" },
          { name: "バケット @イーアスつくば店" },
          { name: "コスモス", starred: true },
          { name: "ミートシノワ: ハンバーグ" },
          { name: "バーガーズカフェWikiwiki: ハンバーガ" },
        ],
      },
      {
        name: "その他",
        restaurants: [
          { name: "薔薇絵亭: ロシア料理", starred: true },
          { name: "メヒコ: シーフード料理", starred: true },
          { name: "アリーズ・ケバブ: ケバブ" },
          {
            name: "本格韓国料理 BabSang（バブサン）: 韓国料理",
            unvisited: true,
          },
        ],
      },
    ],
  },
  {
    name: "カレー",
    restaurants: [
      { name: "ナマステキッチン" },
      { name: "ジュエル オブ インディア" },
      { name: "Guns" },
      { name: "アイマン" },
      { name: "ニューミラ", unvisited: true },
      { name: "Spice curry TRIGGER", unvisited: true },
      { name: "ストリートス", unvisited: true },
      { name: "kalak（カラク）", unvisited: true },
      { name: "アヤカリ亭", unvisited: true },
    ],
  },
  {
    name: "焼肉",
    restaurants: [
      { name: "ジンギスカン喜羊羊", starred: true },
      { name: "牛角 @つくばテクノパーク桜店" },
      { name: "楽蔵" },
      { name: "高麗" },
      { name: "焼肉・しゃぶしゃぶれんが亭" },
      { name: "熟成焼肉いちばん @つくば学園店" },
      { name: "韓国料理 炭火焼肉 ハンアリ", unvisited: true },
      { name: "焼肉 平城苑 つくば学園店", unvisited: true },
    ],
  },
  {
    name: "居酒屋・バー",
    subgenres: [
      {
        name: "居酒屋",
        restaurants: [
          { name: "大将別館", starred: true },
          { name: "灯禾軒（とうかけん）", starred: true },
          { name: "金治（きんじ）", starred: true },
          { name: "わかたろう", starred: true },
          { name: "焼酎天国 ゆず家", starred: true },
          { name: "あさひや", starred: true },
          { name: "馬力ゃ和", starred: true },
          { name: "あじ彩", starred: true },
          { name: "酒食みなき", starred: true },
          { name: "カリビアンカフェ", starred: true },
          { name: "ツインピークス", starred: true },
          { name: "ごはん処 呑み処 ご褒美カロリ", starred: true },
          { name: "ガーリーショット" },
          { name: "ばほばほ" },
          { name: "寅とさくら" },
          { name: "あっぱれ" },
          { name: "寛ぎ個室×ダイニング居酒屋 和楽 つくば" },
          { name: "居酒屋 新世界" },
          { name: "むらさき" },
          { name: "四十八漁場 @つくば店" },
          { name: "アポロ" },
          { name: "焼きもの家 慶" },
          { name: "茨城地のもの わらやき料理 たたきの一九 @つくば店" },
          { name: "さん吉 @つくば店" },
          { name: "びすとろ椿々 cin‐cin" },
          { name: "おもてなし" },
          { name: "焼鳥ふくろう" },
          { name: "九太郎" },
          { name: "串かつ でんがな BiViつくば店" },
          { name: "はなぶさ", unvisited: true },
        ],
      },
      {
        name: "バー・バル",
        restaurants: [
          { name: "Bettei", starred: true },
          { name: "特製飯屋 Highway", starred: true },
          { name: "ホワイトバジル", starred: true },
          { name: "イタメシヤBAFFI", starred: true },
          { name: "三浦飲食堂", starred: true },
          { name: "BAR DALI" },
          { name: "Engi" },
          { name: "ALPACA DINING" },
          { name: "クルーズ" },
          { name: "古民家バル たまり", unvisited: true },
          { name: "だだ食堂", unvisited: true },
          { name: "カンビオ", unvisited: true },
          { name: "wine stand 43ponte", unvisited: true },
          { name: "naked bar", unvisited: true },
          { name: "東京バル GardenTerrace", unvisited: true },
        ],
      },
      {
        name: "その他",
        restaurants: [
          { name: "つくばワイナリー", starred: true },
          { name: "BBQ DAYS" },
        ],
      },
    ],
  },
  {
    name: "ファミレス・ファストフード",
    subgenres: [
      {
        name: "ファミレス",
        restaurants: [
          { name: "ガスト @つくばテクノパーク桜店" },
          { name: "デニーズ @筑波学園都市店" },
          { name: "サイゼリヤ @トナリエつくばスクエア店" },
          { name: "サイゼリヤ @つくば松代店" },
          { name: "ココス @学園天久保店" },
          { name: "ココス @テクノパーク桜店" },
          { name: "ココス @つくば小野崎店" },
          { name: "オリーブの丘 @つくば研究学園店" },
          { name: "エルトリート @つくば学園店: メキシコ料理" },
          { name: "しゃぶ葉 @つくば店" },
          { name: "びっくりドンキー @つくば中央店", unvisited: true },
          { name: "ばんどう太郎 @つくば学園店", unvisited: true },
          { name: "和食さと @つくば店", unvisited: true },
        ],
      },
      {
        name: "牛丼",
        restaurants: [
          { name: "松屋 @つくば西大通り店" },
          { name: "松屋 @つくば東大通店" },
          { name: "吉野家 @つくば天久保店" },
          { name: "すき家 @つくば天久保店" },
          { name: "ジョイフル @つくば桜店" },
        ],
      },
      {
        name: "バーガー",
        restaurants: [
          { name: "マクドナルド @つくば学園店" },
          { name: "マクドナルド @つくば研究学園店" },
          { name: "マクドナルド @イーアスつくば店" },
          { name: "バーガーキング @トナリエクレオつくば店" },
          { name: "サブウェイ @イーアスつくば店" },
          { name: "モスバーガー @つくば中央店" },
          { name: "ケンタッキーフライドチキン @筑波学園店" },
        ],
      },
      {
        name: "その他",
        restaurants: [
          { name: "サーティーワンアイスクリーム @イーアスつくば店" },
          { name: "丸亀製麺 @つくば研究学園店" },
          { name: "丸亀製麺 @イーアスつくば店" },
          { name: "ペッパーランチ @イーアスつくば店" },
          { name: "松のや @つくば東大通り店" },
          { name: "カレーハウス CoCo壱番屋 @つくば桜店", unvisited: true },
        ],
      },
    ],
  },
  {
    name: "カフェ・デザート",
    restaurants: [
      { name: "cox", starred: true },
      { name: "moi!kka（モイッカ）", starred: true },
      { name: "トタンコットンカフェ", starred: true },
      { name: "コーヒーファクトリー" },
      { name: "こおひいはうす らんぷ" },
      { name: "ウエスト珈琲ハウス" },
      { name: "コメダ珈琲 @つくば店" },
      { name: "スターバックスコーヒー @筑波大学中央図書館店" },
      { name: "スターバックスコーヒー @イーアスつくば店" },
      { name: "スターバックスコーヒー @つくば研究学園店" },
      { name: "スターバックスコーヒー @トナリエキュート つくば店" },
      { name: "スターバックスコーヒー @筑波大学附属病院店" },
      { name: "茶の木村園" },
      { name: "スぺシャルティコーヒー豆専門店 トライブ" },
      { name: "自家焙煎珈琲 まめぽっと" },
      { name: "SORA CAFE & COOKING ROOM", unvisited: true },
      { name: "SugayaCoffee", unvisited: true },
      { name: "カフェ クレマチス", unvisited: true },
      { name: "N's cafe", unvisited: true },
      { name: "千年一日珈琲焙煎所 Cafe", unvisited: true },
      { name: "Rainbow cafe @つくば店", unvisited: true },
      { name: "コナズ珈琲 @つくば店", unvisited: true },
    ],
  },
  {
    name: "学食",
    restaurants: [
      { name: "本部棟レストラン", starred: true },
      { name: "大学会館レストラン 筑波デミ", starred: true },
      { name: "医学食堂" },
      { name: "一学食堂" },
      { name: "二学食堂" },
      { name: "粉とクリーム" },
      { name: "第3エリア名店街" },
      { name: "日本国際学園大学 学生食堂" },
      { name: "カフェ マルハバン" },
      { name: "春日食堂" },
      { name: "スープファクトリー" },
    ],
  },
  {
    name: "カラオケ",
    restaurants: [
      { name: "カラオケまねきねこ @つくば店" },
      { name: "BANBAN @つくば店" },
      { name: "BANBAN @つくば学園店" },
      { name: "カラオケ ボイス" },
      { name: "ビッグエコー @つくば天久保店（モナコ店）" },
      { name: "カラオケレインボー @つくば店" },
    ],
  },
];
